### ISSUE TITLE
Link to JSFiddle, CodePen Contributions

### ISSUE THREAD

**Issue by ghost** [xeolabs/xeogl#16]
On the xeoEngine website, consider providing hashtag link to community created examples on JSFiddle, CodePen, CSSDeck. I have one example to post right now - a simple voxel editor.
https://jsfiddle.net/5ek3w0p8/8/

**Comment by quaxquax** [comment]
Kudos for the voxel editor. Neat example to showcase xeoEngine.

**Comment by xeolabs** [comment]
Thanks this is great! The voxel editor also demonstrates the primitive picking really clearly. I'll get a hashtag link sorted out tonight.

**Comment by xeolabs** [comment]
@philmaker1  I just made a [fork of your demo](https://jsfiddle.net/lindsaykay/9q9rr6rf/2/) where I've shared the same PhongMaterial and BoxGeometry instances amongst all the GameObjects. 

That makes for a smaller memory footprint, and also improves rendering speed because then, when rendering a frame,  XEO will be able to bind the WebGL state for the PhongMaterial and BoxGeometry once before rendering all the GameObjects, instead of binding a unique PhongMaterial and BoxGeometry instance for each GameObject individually.

**Comment by philmaker1** [comment]
I made some updates. I added steps in addition to cubes. I started building a toolbar using a secondary canvas. The toolbar is one reason why I'm trying to get components serialization working - so I can serialize components more easily from the primary scene to the toolbar scene.
https://jsfiddle.net/philmaker/mLj6znkt/embedded/result/
I started to work on the memory footprint best practice using an assets object but I haven't finished that yet. But I will make it happen.
Soon I'll be working on dynamically rendering art patterns to textures.
