### ISSUE TITLE
3d snapshot is not working because of this.contextAttr.preserveDrawingBuffer=false

### ISSUE THREAD

**Issue by emiyalee1005** [xeolabs/xeogl#161]
##### Description of the problem 

i can not snapshot the canvas by either using canvas.todataurl or stock viewer.getsnapshot() /*bimsurfer also*/ api,because preserveDrawingBuffer of webgl-context is set to false 

##### xeogl version

- [ ] Dev
- [x] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
Yes this is a tricky one because the zSpace display [used by these demos](http://xeogl.org/examples/#effects_zspace_geometries) only works with preserveDrawingBuffer set false.  

Solution would be:

When relying on the default Scene provided by xeogl, then we would be able to configure what context attributes that xeogl will set on the default Scene's canvas, ie.

````javascript
xeogl.defaultContextAttr.preserveDrawingBuffer = true;

// Creates default Scene at this point, with default context attributes as defined above
var myEntity = new xeogl.Entity({...}); 
````

and when creating your own scene, make it so that that your ````preserveDrawingBuffer``` can override xeogl's:

````
var myScene = new xeogl.Scene({
    contextAttr: {
        preserveDrawingBuffer: true
   }
});
````

I'll do this one after the touch events.

**Comment by xeolabs** [comment]
Just fixed this in master. xeogl now supports two snapshot modes - see these examples: 

* [asynchronously](http://xeogl.org/examples/#canvas_snapshot_asynchronous) - works on any ````xeogl.Scene````
* [synchronously](http://xeogl.org/examples/#canvas_snapshot_asynchronous) - only works with ````xeogl.Scene```` configured with ````preserveDrawingBuffer:true````, which incurs performance penalty
