### ISSUE TITLE
 clarity of the xeogl glass is not ideal

### ISSUE THREAD

**Issue by yoyomule** [xeolabs/xeogl#198]
##### Description of the problem 
I compared the glass and threejs of the xeogl system. The clarity of the xeogl glass is not ideal. Do I need to make some adjustments?
...

[vianney_house_2.zip](https://github.com/xeolabs/xeogl/files/1294516/vianney_house_2.zip)
![xeogl](https://user-images.githubusercontent.com/10000818/30304793-dc18c9f6-97a1-11e7-8afa-536bf911c35a.png)
![threejsgtlfviewer](https://user-images.githubusercontent.com/10000818/30304794-dc1f67c0-97a1-11e7-8604-b4c70e8c4196.png)

**Comment by xeolabs** [comment]
I'll investigate. Do you know the (eye, look, up) camera position for these scresnshots?

**Comment by xeolabs** [comment]
The reason is that xeogl and THREE just use different WebGL blend functions.  xeogl was using ````gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA)```` while THREE uses ````gl.blendFuncSeparate(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA, gl.ONE, gl.ONE_MINUS_SRC_ALPHA);````.

There are advantages and disadvantages with each, but for now, I have changed xeogl to use the same function as THREE.js,  since it seems to be the best for rendering windows like these.

Fix confirmed with this example:

http://xeogl.org/examples/#featured_VianneyHouse2

![screenshot from 2017-09-12 08-46-01](https://user-images.githubusercontent.com/83100/30311736-ff691a88-9796-11e7-9b11-4b4d1bfe95cb.png)

Going forward, I will see if I can make that configurable.
