### ISSUE TITLE
Draco support question

### ISSUE THREAD

**Issue by koeckc** [xeolabs/xeogl#294]
First of all thx for providing us this great lib !! 

Not really an issue more of a question... do you support or plan to support draco compression for gltf models ... i gave it try with
https://github.com/AnalyticalGraphicsInc/gltf-pipeline and i get an error on loading the model
```

Uncaught TypeError: Cannot read property '_buffer' of undefined
    at loadAccessor (glTFModel.js:820)
    at loadAccessors (glTFModel.js:798)
    at glTFModel.js:655
    at glTFModel.js:678
    at glTFModel.js:697

```

##### Browser
- [x ] Chrome
##### OS
- [x] OSX

Regards

**Comment by xeolabs** [comment]
You're welcome! 

Yes Draco is on the roadmap - I'm actually expecting a PR to add Draco support to GLTFModel, some time next month. There's a startup that has implemented it and generously intends to contribute it :)

**Comment by koeckc** [comment]
Great stuff thx

**Comment by lgwebdream** [comment]
I also encountered the same problem. Can you use it now? Very urgent, thank you for your answer.

**Comment by xeolabs** [comment]
Unfortunately the startup who offered to merge their Draco support informed me that they no longer have the time to make the PR.

**Comment by lgwebdream** [comment]
Take the liberty to ask, will the future days support Draco?
I especially like the xeogl you developed and it's a loyal user. I hope that I can support it, so I can solve the problem that the loading time is too long because the Gltf model is too large. I wish you a happy life and hope that xeogl is getting better and better.

**Comment by lgwebdream** [comment]
Take the liberty to ask, will the future days support Draco?
I especially like the xeogl you developed and it's a loyal user. I hope that xeogl can support it, so that it can solve the problem that the loading time is too long because the Gltf model is too large. I wish you a happy life and hope that xeogl is getting better and better.
